accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    
]

auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

articles/models.py
from django.db import models
from accounts.models import User
from django.conf import settings
from django.contrib.auth import get_user_model
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    # 유저 모델을 참조하는 경우
    # 방법1. (권장하지 않음)
    # user = models.ForeignKey(, on_delete=models.CASCADE)

    # 방법2. (권장) settings.AUTH_USER_MODEL=='accounts.User'
    # user = models.ForeeignKey(seetings.AUTH_USER_MODEL, on_delete=models.CASCADE )

    # 방법3. (권장)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

accounts/forms.py
from . models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields 

class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = '__all__'
        exclude = ('user', )
        # fields=('title', 'content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')

    else: # 빈 종이 보여줌
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'signup.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            #로그인
            auth_login(request, form.get_user())

            return redirect('articles:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'login.html', context )


def logout(request):
    auth_logout(request)

    return redirect('accounts:login')

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm
from .models import Article

# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }
    return render(request, 'index.html', context)

def create(request):
    if request.method =='POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')

    else:
        form = ArticleForm()

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)

accounts/templates/login.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">

    </form>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method = "POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method ="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>index</h1>

    {% for article in articles %}
    <h3>{{ article.title }}</h3>
    <p>{{ article.user }}</p>
    <hr>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'articles:create' %}">Create</a>
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              <a class="nav-link disabled" >{{ user }}</a>

              {% else %}
              <a class="nav-link active" href="{% url 'accounts:signup' %}">Signup</a>
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              
              {% endif %}
            </div>
          </div>
        </div>
    </nav>


    <div class="container">
        {% block body %}
        
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>